version: "3.9"

services:
  web_rr:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:${PORT}"
  postgres:
    environment:
      POSTGRES_DB: postgres_rr
      POSTGRES_PASSWORD: <postgres_pwd>
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
  celery_worker:
    restart: always
    build:
      context: .
    command: celery -A redrope_34592 worker --loglevel=info
    volumes:
      - ./:/opt/webapp
    depends_on:
      - web_rr
      - postgres
      - redis
  celery_beat:
    restart: always
    build:
      context: .
    command: celery -A redrope_34592 beat --loglevel=info
    volumes:
      - ./:/opt/webapp
    depends_on:
      - web_rr
      - postgres
      - redis

volumes:
  postgres-data:
