# Generated by Django 2.2.28 on 2022-05-30 16:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Event title')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Event description')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Event location')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='Event image'), blank=True, null=True, size=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Event price')),
                ('date', models.DateField(verbose_name='Event date')),
                ('categories', models.ManyToManyField(related_name='category_events', to='home.Category', verbose_name='Event category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
