# Generated by Django 2.2.28 on 2022-05-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
