# Generated by Django 2.2.28 on 2022-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220530_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='Category image'),
        ),
    ]
