# Generated by Django 2.2.28 on 2022-05-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220531_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='address_longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
    ]
