# Generated by Django 2.2.28 on 2022-06-06 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='going_event', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
