# Generated by Django 2.2.28 on 2022-06-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220609_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventregistration',
            name='attendee',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of attendees'),
        ),
    ]
