# Generated by Django 2.2.28 on 2022-06-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_aboutus_privacypolicy_termsandcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='termsandcondition',
            name='heading',
        ),
    ]
