# Generated by Django 2.2.28 on 2022-06-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220613_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(blank=True, max_length=400, null=True, verbose_name='Question')),
                ('response', models.TextField(verbose_name='Response')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
