# Generated by Django 2.2.28 on 2022-06-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
