# Generated by Django 2.2.28 on 2022-06-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_privacypolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermsAndCondition',
        ),
    ]
