# Generated by Django 2.2.28 on 2022-06-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_termsandcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=600, null=True, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Content Body')),
            ],
            options={
                'verbose_name_plural': 'FeedBacks and Supports',
            },
        ),
    ]
