# Generated by Django 2.2.28 on 2022-06-22 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_feedbacksupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_location',
            field=models.BooleanField(default=False, verbose_name='Use primary location'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='event',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='event',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Zip code'),
        ),
        migrations.CreateModel(
            name='BottleService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('person', models.PositiveIntegerField(default=1, verbose_name='Number of persons')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='bottle_service',
            field=models.ManyToManyField(blank=True, related_name='event', to='home.BottleService', verbose_name='Bottle service'),
        ),
    ]
