# Generated by Django 2.2.28 on 2022-06-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220622_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bottle_service',
            field=models.ManyToManyField(blank=True, related_name='event', to='home.BottleService', verbose_name='Bottle service'),
        ),
    ]