# Generated by Django 2.2.28 on 2022-06-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220625_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='primary_location',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Event end time'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Event start time'),
        ),
    ]
