# Generated by Django 2.2.28 on 2022-06-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220625_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventregistration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction ID'),
        ),
    ]
