# Generated by Django 2.2.28 on 2022-06-26 01:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0027_usereventregistration_transaction_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usereventregistration',
            unique_together={('user', 'event')},
        ),
    ]
