# Generated by Django 2.2.28 on 2022-07-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventregistration',
            name='bottle_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_registration', to='home.BottleService', verbose_name='Event'),
            preserve_default=False,
        ),
    ]
