# Generated by Django 2.2.28 on 2022-07-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_usereventregistration_bottle_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventregistration',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'pending'), ('Succeeded', 'succeeded'), ('Failed', 'failed')], max_length=50, null=True, verbose_name='Payment Status'),
        ),
    ]
