# Generated by Django 2.2.28 on 2022-08-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_usereventregistration_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventregistration',
            name='bottle_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registration', to='home.BottleService', verbose_name='Event'),
        ),
    ]
