# Generated by Django 2.2.28 on 2022-09-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20220829_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventregistration',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Status'),
        ),
    ]
