# Generated by Django 2.2.28 on 2022-12-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_usereventregistration_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventregistration',
            name='available_slots',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of available_slots'),
        ),
    ]
