# Generated by Django 2.2.28 on 2023-04-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_usereventregistration_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Venue name'),
        ),
    ]
