# Generated by Django 2.2.28 on 2023-04-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
    ]
