# Generated by Django 2.2.28 on 2023-04-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_event_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereventregistration',
            name='payment_intent_id',
        ),
        migrations.AddField(
            model_name='usereventregistration',
            name='charge_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Charge ID'),
        ),
    ]
