# Generated by Django 2.2.28 on 2023-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_feedbacksupport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventregistration',
            name='stripe_fee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stripe Fee'),
        ),
    ]
