# Generated by Django 2.2.28 on 2023-05-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_usereventregistration_stripe_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usereventregistration',
            options={'verbose_name_plural': 'Event Registrations'},
        ),
    ]
