# Generated by Django 2.2.28 on 2023-05-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20230521_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='bottleservice',
            options={'verbose_name_plural': 'Bottle Services'},
        ),
        migrations.AlterModelOptions(
            name='favoriteevent',
            options={'verbose_name_plural': 'Favorite Events'},
        ),
    ]
