# Generated by Django 2.2.28 on 2023-05-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20230521_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventregistration',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Channel'),
        ),
    ]
