# Generated by Django 2.2.28 on 2023-06-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_usereventregistration_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventregistration',
            name='balance_channel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Balance Payment Channel'),
        ),
        migrations.AddField(
            model_name='usereventregistration',
            name='balance_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Charge ID'),
        ),
        migrations.AddField(
            model_name='usereventregistration',
            name='balance_paid',
            field=models.BooleanField(default=False, verbose_name='Balance Paid'),
        ),
    ]
