# Generated by Django 2.2.28 on 2023-06-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20230622_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventregistration',
            name='balance_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Balance Charge ID'),
        ),
    ]
