# Generated by Django 2.2.28 on 2023-08-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20230623_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereventregistration',
            name='available_slots',
        ),
        migrations.AddField(
            model_name='bottleservice',
            name='available_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of available_slots'),
        ),
    ]
