# Generated by Django 2.2.26 on 2022-05-25 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_tc',
            field=models.BooleanField(default=False, verbose_name='Accept Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
