# Generated by Django 2.2.28 on 2022-05-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_event'),
        ('users', '0002_auto_20220525_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interest_users', to='home.Category', verbose_name='Interest'),
        ),
    ]
