# Generated by Django 2.2.28 on 2022-07-18 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220718_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('[+-/%#$@!~^&*()]', inverse_match=True)], verbose_name='Name of User'),
        ),
    ]
