# Generated by Django 2.2.28 on 2022-08-03 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220718_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Name', max_length=255, validators=[django.core.validators.RegexValidator('[+-/%#$@!~^&*()1234567890]', inverse_match=True)], verbose_name='Name of User'),
            preserve_default=False,
        ),
    ]
