# Generated by Django 2.2.28 on 2022-08-21 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220803_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('[+-/%#$@!~^&*()1234567890]', inverse_match=True)], verbose_name='Name of User'),
        ),
    ]
