# Generated by Django 2.2.28 on 2022-09-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220821_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alt_profile_picture',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Alt Profile Picture'),
        ),
    ]
