# Generated by Django 2.2.28 on 2022-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_alt_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alt_profile_picture',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Profile Picture'),
        ),
    ]
