# Generated by Django 2.2.28 on 2022-09-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220926_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accept_tc',
            field=models.BooleanField(default=True, verbose_name='Accept Terms and Conditions'),
        ),
    ]
