# Generated by Django 2.2.28 on 2023-04-26 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_stripe_connect_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_bank_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Bank Account ID'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='currency',
            field=models.CharField(default='USD', max_length=50, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payout_id',
            field=models.CharField(default='0', max_length=50, verbose_name='Payout ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Connect Account ID'),
        ),
    ]
