# Generated by Django 2.2.28 on 2023-05-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_is_stripe_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Location'),
        ),
    ]
