# Generated by Django 2.2.28 on 2023-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_push_notification',
            field=models.BooleanField(default=False, verbose_name='Subscribed For Push-Notification'),
        ),
    ]
