export const APP_MAIN = "#FFF"
export const APP_MAIN_2 = "#06A2E5"
export const LIGHT_GREY = "#d5dade"
export const GUL_GRAY = "#96A7B0";
export const GRAY_MEDIUM = "#7f878b";
export const THEME_TEXT_COLOR = "#04171F";
export const BORDER_COLOR = "#143C4C"
export const INPUT_BG_COLOR = "#f6f6f6";
export const ICON_BG = "#ebeded"
export const MAIN_BG = "#fbfbfd"
export const WHITE = "#fff"
export const RED = "#FF4B26"
export const TAG_HEADER = "#547C8C"
export const TEXT_COLOR_2 = "#231f20"
export const INPUT_BG_COLOR_2= "#dededf"
